
service: selenium-layer


provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-2
  timeout: 900

layers:
  selenium:
    path: selenium
    CompatibleRuntimes: [
      "python3.7"
    ]
  chromedriver:
    path: chromedriver
    description: chrome driver layer
    CompatibleRuntimes: [
      "python3.7"
    ]
resources:
  Outputs:
    SeleniumLayerExport:
        Value:
          Ref: SeleniumLambdaLayer
        Export:
          Name: SeleniumLambdaLayer
    ChromedriverLayerExport:
      Value:
        Ref: ChromedriverLambdaLayer
      Export:
        Name: ChromedriverLambdaLayer